# dvc.yaml
stages:
  preprocess:
    cmd: python src/preprocess_spark.py
    deps:
      - src/preprocess_spark.py
      - data/diabetes.csv
    outs:
      - data/diabetes_processed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/diabetes_processed.csv
    outs:
      - models/model.pkl
      - data/X_test.csv
      - data/y_test.csv
    metrics:
      - metrics.json:
          cache: false

  validate:
    cmd: python src/validate.py
    deps:
      - src/validate.py
      - metrics.json